- name: configure cart
  hosts: cart
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable default nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create roboshop cart
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: download the cart
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
        dest: /tmp/cart.zip

    - name: extract cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    
    - name: daemon reload the system service
      ansible.builtin.systemd_service:
        daemon_reload: true
    
    - name: enable and start the system service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes