- name: configure catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable default nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: download the catalogue
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
        dest: /tmp/catalogue.zip

    - name: extract catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: etc/systemd/system/catalogue.service
    
    - name: daemon reload the system service
      ansible.builtin.systemd_service:
        daemon_reload: true
    
    - name: enable and start the system service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy mongo repo
      ansible.builtin.copy:
        src: cmongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb-mongosh
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongodb.pract.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: loading the products
      ansible.builtin.shell: mongosh --host mongodb.pract.site </app/db/master-data.js
      when: catalogue_output.stdout | int < 0

    






