- name: configure shipping
  hosts: user
  become: yes
  tasks:
    - name: install java and python
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: installed
        loop:
        - maven
        - mysql

    - name: create roboshop cart
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: download the cart
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
        dest: /tmp/cart.zip

    - name: extract cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
    
    - name: install maven dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: rename jar files
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
      args:
        chdir: /app
      
    - name: copy cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    
    - name: daemon reload the system service
      ansible.builtin.systemd_service:
        daemon_reload: true
    
    - name: enable and start the system service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: loading schema
      ansible.builtin.command:  mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < "{{ item }}"
        loop: 
        



